# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-ast
        types: [python]
    -   id: check-json
        types: [json]
    -   id: pretty-format-json
        types: [json]
        args: [--autofix, --indent, '2', --top-keys, "name,desc,$schema"]
-   repo: local
    hooks:
    -   id: black
        name: black
        entry: black
        language: system
        types: [python]
    -   id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
    -   id: testcase-validate
        name: testcase-validate
        entry: python
        language: system
        types: [python]
        files: ^testcases/
        args: [testscript, validate]
        always_run: true
        description: Validate testcases
