name: "Validate Testcases"

on: push

permissions:
  contents: read

jobs:
  validate-testcases:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: "^3.10"
          check-latest: true

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Validate
        run: python ./testscript/test.py validate
