name: "Validate Testcases"

on:
  push:
    branches:
      - main
      - 'testcases/*'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: "^3.10"
          check-latest: true

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Validate File Structure
        run: python ./testscript/test.py validate -v

      - name: Validate Manifests
        uses: cardinalby/schema-validator-action@v3
        with:
          file: 'testcases/*/manifest.json'
          schema: 'testcases/schema.json'
